# Generated by Django 5.2.14 on 2026-05-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='quantity_units',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='value_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
