# Generated by Django 5.2.14 on 2026-05-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_cost_per_unit_project_quantity_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cost_per_unit',
        ),
    ]
