# Generated by Django 5.2.14 on 2026-06-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
