# Generated by Django 5.2.16 on 2026-07-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workflow_demo_mode',
            field=models.BooleanField(default=False),
        ),
    ]
