# Generated by Django 5.2.14 on 2026-06-07 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_partner'),
        ('materials', '0001_initial'),
        ('projects', '0005_project_cost_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('requested', 'Solicitado'), ('approved', 'Aprovado'), ('purchased', 'Comprado'), ('delivered', 'Entregue')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_orders', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='materials.materialorder')),
            ],
        ),
    ]
