# Generated by Django 5.2.14 on 2026-06-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_materialorder_materialorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialorderitem',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='materialorderitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='materialorderitem',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
