# Generated by Django 5.2.14 on 2026-06-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_materialorderitem_unit_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialorderitem',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='materialorder',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
