# Generated by Django 5.2.14 on 2026-06-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_remove_materialorderitem_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
