# Generated by Django 5.2.14 on 2026-06-11 02:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_materialorder_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialorderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='materialorderitem',
            name='unit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materialorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='MaterialOrderSupplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('attachment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='materials.materialorder')),
            ],
        ),
        migrations.AddField(
            model_name='materialorderitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='materials.materialordersupplier'),
        ),
    ]
