# Generated by Django 5.2.14 on 2026-06-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_remove_materialorderitem_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialorderitem',
            old_name='unit_value',
            new_name='total_value',
        ),
        migrations.AlterField(
            model_name='materialorderitem',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
