# Generated by Django 5.2.14 on 2026-06-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_rename_unit_value_materialorderitem_total_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='order_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='order_date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
