# Generated by Django 5.2.14 on 2026-05-22 16:46

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatephoto',
            name='image',
            field=core.fields.CompressedImageField(upload_to='updates/%Y/%m/'),
        ),
    ]
