# Generated by Django 5.2.14 on 2026-05-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_alter_updatephoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='updates/videos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link para vídeo (YouTube, Vimeo, etc)', null=True),
        ),
    ]
