# Generated by Django 5.2.14 on 2026-06-01 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_clientcontribution_expensecategory_and_more'),
        ('projects', '0004_remove_project_cost_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='projects.project'),
        ),
    ]
