# Generated by Django 5.2.14 on 2026-05-22 16:46

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=core.fields.CompressedImageField(blank=True, null=True, upload_to='employees/'),
        ),
    ]
